### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by 6ecuk** [interiorem/elliptics#240]
Good evening. Got question about this fork. As i know this fork currently used by Yandex. So my question - is currently version backward compatible with reverbrain/elliptics ?

**Comment by shaitan** [comment]
Hi, Eugene!

Backward compatibility wasn't in goals of this fork, but it should be at the follow level:
- should work but no guarantees:
  - **previous blob's format is supported**: `interiorem/elliptics & interiorem/eblob` should correctly work with blobs generated by `reverbrain/elliptics & reverbrain/eblob`
  - **previous protocol is supported (may be dropped with the next major release)**: apps, that are built for `reverbrain/elliptics`, should correctly work with `interiorem/elliptics` server, but they should use `reverbrain/elliptics` libraries
- definitely doesn't work:
  - **config was changed**: `interiorem/elliptics & interiorem/eblob` don't work with config file for `reverbrain/elliptics & reverbrain/eblob` and vice a versa
  - **blob's format was extended**: `reverbrain/elliptics & reverbrain/eblob` don't work with blobs generated by `interiorem/elliptics & interiorem/eblob`
  - **API/ABI was broken**: 
    - apps built for `reverbrain/elliptics` don't work with `interiorem/elliptics` libraries
    - `interiorem/elliptics` scrips and utils (`dnet_recovery`, `dnet_client`, `dnet_ioclient` etc.) don't work with `reverbrain/elliptics`
    - `interiorem/elliptics` doesn't work with `reverbrain/eblob` as well as `reverbrain/elliptics` doesn't work with `interiorem/eblob`
  - **protocol was extended**: apps, that are built for `interiorem/elliptics`, don't work with `reverbrain/elliptics`


Relevant for versions:
```
interiorem/elliptics = v2.27.9.3
interiorem/eblob = v0.24.5

reverbrain/elliptics = v2.26.11.1
reverbrain/eblob = v0.23.14
```

**Comment by 6ecuk** [comment]
Thanks for detailed response. 
If there any sense to migrate on this fork, or it only for internal usage in Yandex?
